version: '3.1'
services:
  dbtienda:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: zx76wbz7FG89k19
    networks:
      - skynet
    ports:
      - 33306:3306

  adminertienda:
    image: adminer
    restart: "no"
    networks:
      - skynet
    ports:
      - 8181:8080
  
  correotienda:
    image: marooou/postfix-roundcube
    environment:
      ADMIN_USERNAME: root
      ADMIN_PASSWD: zx76wbz7FG89k19
      DOMAIN_NAME: iesvdc.lan
      USERS:
        - baltany:admin
    ports:
      - 25:25 
      - 8282:80 
      - 110:110 
      - 143:143 
      - 465:465 
      - 993:993 
      - 995:995
    networks:
      - skynet
    
networks:
  skynet:
